name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature] - "
labels: ["Feature", "To Do"]
type: "Feature"
projects: "github/8"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Briefly describe the feature or improvement."
      placeholder: "E.g., Add a dark mode to the application."

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Why is this feature needed?"
      placeholder: "E.g., Dark mode improves usability in low light environments."

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "How do you suggest implementing this feature?"
      placeholder: "E.g., Add a toggle option in the settings menu."

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      options:
        - label: "Feature is clearly defined"
        - label: "Meets proposed solution"
        - label: "Tests considered"

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Info"
      placeholder: "Optional: Any extra context or references."
